/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controladores.controlador_Registro;

import javax.swing.*;

/**
 *
 * @author ayola
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_login_ingresar = new javax.swing.JButton();
        txt_login_usuario = new javax.swing.JTextField();
        txt_login_contraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_login_registrarse = new javax.swing.JButton();
        chkUsuario = new javax.swing.JCheckBox();
        chkProveedor = new javax.swing.JCheckBox();
        chkAdmin = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio de sesion");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 180, -1));

        btn_login_ingresar.setBackground(new java.awt.Color(0, 102, 204));
        btn_login_ingresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_login_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_login_ingresar.setText("Ingresar");
        btn_login_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_ingresarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_login_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 180, 30));
        jPanel4.add(txt_login_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 180, -1));
        jPanel4.add(txt_login_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        btn_login_registrarse.setBackground(new java.awt.Color(0, 102, 204));
        btn_login_registrarse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_login_registrarse.setForeground(new java.awt.Color(255, 255, 255));
        btn_login_registrarse.setText("Registrarse");
        btn_login_registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_registrarseActionPerformed(evt);
            }
        });
        jPanel4.add(btn_login_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 190, 30));

        chkUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkUsuario.setForeground(new java.awt.Color(255, 255, 255));
        chkUsuario.setText("Usuario");
        chkUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUsuarioActionPerformed(evt);
            }
        });
        jPanel4.add(chkUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        chkProveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkProveedor.setForeground(new java.awt.Color(255, 255, 255));
        chkProveedor.setText("Proovedor");
        chkProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProveedorActionPerformed(evt);
            }
        });
        jPanel4.add(chkProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        chkAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkAdmin.setForeground(new java.awt.Color(255, 255, 255));
        chkAdmin.setText("Admin");
        chkAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAdminActionPerformed(evt);
            }
        });
        jPanel4.add(chkAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newpackage/Diseño sin título (1).png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 800, 470));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void btn_login_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_ingresarActionPerformed
    String email = txt_login_usuario.getText().trim();
String contraseña = txt_login_contraseña.getText().trim();
 
if (!chkUsuario.isSelected() && !chkAdmin.isSelected() && !chkProveedor.isSelected()) {
    JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de usuario para ingresar");
    return;
}


if (email.equals("admind@gmail.com") && contraseña.equals("123")) {
    
    if (chkUsuario.isSelected()) {
        controlador_Registro.setEmailUsuarioActual(email);
        Vista_usuario vista = new Vista_usuario();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    } 
    else if (chkAdmin.isSelected()) {
        Vista_admin vista = new Vista_admin();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    } 
    else if (chkProveedor.isSelected()) {
        Provedores vista = new Provedores();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }
    return;
}


String[] resultado = controlador_Registro.validarLoginCompleto(email, contraseña);
if (resultado == null) {
    JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos");
    return;
}

String rolEncontrado = resultado[0];  
String emailUsuario = resultado[1];   

if (chkUsuario.isSelected() && rolEncontrado.equals("Usuario")) {
    controlador_Registro.setEmailUsuarioActual(emailUsuario);
    Vista_usuario vista = new Vista_usuario();
    vista.setVisible(true);
    vista.setLocationRelativeTo(null);
    this.dispose();
} 
else if (chkAdmin.isSelected() && rolEncontrado.equals("Admin")) {
    Vista_admin vista = new Vista_admin();
    vista.setVisible(true);
    vista.setLocationRelativeTo(null);
    this.dispose();
} 
else if (chkProveedor.isSelected() && rolEncontrado.equals("Proveedor")) {
    Provedores vista = new Provedores();
    vista.setVisible(true);
    vista.setLocationRelativeTo(null);
    this.dispose();
} 
else {
    JOptionPane.showMessageDialog(this, 
        "El rol seleccionado no coincide con sus credenciales.\nUsted está registrado como: " + rolEncontrado);
}
    }//GEN-LAST:event_btn_login_ingresarActionPerformed

    private void btn_login_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_registrarseActionPerformed
        Registro Ingresar = new Registro();
        Ingresar.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_login_registrarseActionPerformed

    private void chkUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUsuarioActionPerformed
        if (chkUsuario.isSelected()) {
        chkProveedor.setSelected(false);
        chkAdmin.setSelected(false);
        
        
        
    }

    }//GEN-LAST:event_chkUsuarioActionPerformed

    private void chkProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProveedorActionPerformed
        if (chkProveedor.isSelected()) {
        chkUsuario.setSelected(false);
        chkAdmin.setSelected(false);
    }
    }//GEN-LAST:event_chkProveedorActionPerformed

    private void chkAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAdminActionPerformed
        if (chkAdmin.isSelected()) {
        chkUsuario.setSelected(false);
        chkProveedor.setSelected(false);
        
        }
    }//GEN-LAST:event_chkAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_login_ingresar;
    private javax.swing.JButton btn_login_registrarse;
    private javax.swing.JCheckBox chkAdmin;
    private javax.swing.JCheckBox chkProveedor;
    private javax.swing.JCheckBox chkUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPasswordField txt_login_contraseña;
    public javax.swing.JTextField txt_login_usuario;
    // End of variables declaration//GEN-END:variables
}
